### ISSUE TITLE
Remove the top border

### ISSUE THREAD

**Issue by HZSamir** [timomeh/react-native-material-bottom-navigation#101]
Hello,
i'm trying to get rid of the border at the top of this element, with no success so far.
Neither
```javascript
<BottomNavigation
  onTabPress={newTab => {
  this.setState({ activeTab: newTab.key })
  if(newTab.key == 'settings') this.props.navigation.navigate('Settings')
}}
  renderTab={this.renderTab}
  tabs={tabs}
  style={{borderTopWidth:0}}
/>
```
Or
```javascript
renderTab = ({ tab, isActive }) => (
    <IconTab
      isActive={isActive}
      style={{borderTopWidth:0}}
      showBadge={tab.key === 'settings'}
      renderBadge={() => <Badge>2</Badge>}
      style={{borderBottomWidth: isActive ? 2 : 0, borderBottomColor: '#0960bd', paddingHorizontal: 0}}
      key={tab.key}
      label={tab.label}
      renderIcon={this.renderIcon(tab.icon)}
    />
  )
```
helps. I've tried a number of other things as well, to no avail.
See this screenshot:
![screenshot from 2018-08-01 15-54-49](https://user-images.githubusercontent.com/4499783/43529490-533ef28a-95a3-11e8-8832-299066bf36a6.png)

How do I fix this?
Thank you.

**Comment by timomeh** [comment]
Android has a default style of `elevation: 8`. The top-border (shadow) should be gone when using

```js
<BottomNavigation
  style={{ elevation: 0 }}
/>
```

**Comment by timomeh** [comment]
Also, iOS has a default shadow style which you need to override. See here: 
https://github.com/timomeh/react-native-material-bottom-navigation/blob/c970bbfcdf6635de145a9a5da924485f9d17bb26/lib/BottomNavigation.js#L183-L189
(Sent via Mail because I think I broke GitHub.)

**Comment by HZSamir** [comment]
Thank you very much, this is exactly it.
