### ISSUE TITLE
Typo in easings import

### ISSUE THREAD

**Issue by PeterKottas** [timomeh/react-native-material-bottom-navigation#109]
Hi there, just found a rly simple issue.
In https://github.com/timomeh/react-native-material-bottom-navigation/blob/master/lib/PressRippleAnimation.js#L62 you use easyIn
while in https://github.com/timomeh/react-native-material-bottom-navigation/blob/master/lib/utils/easing.js#L3
it's defined as easeInOut

It can lead to some unexpected behavior, just figured you might wanna know about it.

Btw, I love the new rewrite! 👍

**Comment by timomeh** [comment]
That's pretty awesome that you found this typo/bug! Thank you very much. I'm gonna fix this very quick.

_Note: You didn't fill out the issue template. Although you provided all the necessary informations, the issue template always helps every maintainer in every project by having structured reports, informations and generally stay sane. It may sound tedious, but it really helps. Please don't delete it the next time you open an issue in any repo, not limited to mine. Thanks._

**Comment by PeterKottas** [comment]
Cheers man, this was so easy that it just didn't make sense to keep it. Would have created PR myself but I only noticed it afk due to build warning me about this. But in general I agree.
