### ISSUE TITLE
react-navigation: tintColor is undefined when using BottomNavigation

### ISSUE THREAD

**Issue by timomeh** [timomeh/react-native-material-bottom-navigation#11]
When using the icon inside `navigationOptions`, tintColor is undefined. Need to check in TabView.TabBarBottom how and why.

**Comment by timomeh** [comment]
Instead of using react-navigation's `icon: ({ tintColor }) => (<Icon color={tintColor}) />)`, you should use the `activeIcon`-option of react-native-material-bottom-navigation, because it'll look better. Trust me.

**Comment by timomeh** [comment]
But nonetheless, it should work in the next version.

**Comment by Myzel394** [comment]
@timomeh I'm facing the same issue :(
