### ISSUE TITLE
Tab label text is cut off with 5 tabs on iPhone X

### ISSUE THREAD

**Issue by coderdave** [timomeh/react-native-material-bottom-navigation#113]
### Question / Problem
I'm using 5 tabs. The label text however gets cut off on iPhone X layouts. It works fine for the other iOS devices.

Is there a way around this without using the `ShiftingTab`? Because I always want to see the label text.

### Actual behavior

- Far left label text is getting cut off.

### Expected behavior

- Tabs are adjusted accordingly so the label text isn't cut off for iPhone X devices.

### Additional resources

![tab](https://user-images.githubusercontent.com/964751/48429815-df492680-e73b-11e8-809b-3759e8bd8b96.png)

### Environment

I'm using version 1.0.2 of this library.

**Comment by fedeerbes** [comment]
Hi @coderdave i had the same problem and added this style to < FullTab/ > component. { minWidth: null, maxWidth: null }, in order to make room for 5 tabs

**Comment by coderdave** [comment]
Ok, that will be a fine workaround for now.
