### ISSUE TITLE
Customise navigation bar -help wanted

### ISSUE THREAD

**Issue by lutakyn** [timomeh/react-native-material-bottom-navigation#117]
### What kind of Issue is this?
Discussion / Feature Request 
I am looking for a way we can customise the navigation button. I can't find any other way to go around the type of navigation I want to do

### Actual behavior

Currently the tab bar can't be styled with react style 

### Expected behavior
This is the kind of buttom navigation I want to do. You can give me guidelines to do that 
[](http://imgur.com/1RgvJec)

| software                                | version
| --------------------------------------- | ------- 
| react-native-material-bottom-navigation |
| react-native or expo                    |
| node                                    |
| npm or yarn                             |

**Comment by lutakyn** [comment]
https://m.imgur.com/1RgvJec

This is the kind of navigation needed

**Comment by timomeh** [comment]
What you want is something Google calls the "App Bar Bottom". It's not possible with this library. I wrote it in the readme:

> Google updated the Material Guidelines on Google I/O 2018 with new specifications, including a slightly changed Bottom Navigation and a new "App Bar Bottom" with a FAB in a centered cutout. react-native-material-bottom-navigation uses the older specs.
