### ISSUE TITLE
ontabPress doesn't work...maybe becuzof createMaterialTopTabNavigator

### ISSUE THREAD

**Issue by TrustOne** [timomeh/react-native-material-bottom-navigation#126]
I'm trying to use this lib, but ontabPress doesn't work,, 
       
I can see bottom tabs I made, but press function not working..

maybe because  I already use createMaterialTopTabNavigator.. right?/

here is my screen.

![image](https://user-images.githubusercontent.com/2093148/59819186-c227a680-9361-11e9-85ef-f167efff0b69.png)

the text three hello is bottom tab s

software | version
-- | --
react-native-material-bottom-navigation | lates
react-native or expo | react-native
node | 10.10.0
npm or yarn | 6.4.1 npm

**Comment by timomeh** [comment]
You didn't fill out the issue template. Without any code, I can't help you.

Please create a new issue, fill out the issue template and include your code!
