### ISSUE TITLE
Bottom navigation zIndex

### ISSUE THREAD

**Issue by RideTheSun** [timomeh/react-native-material-bottom-navigation#137]
### **Question / Problem**

![2020-03-02_17-44-53](https://user-images.githubusercontent.com/5754944/75686692-b987be00-5cad-11ea-8840-91aabe06b8cc.png)
I'm trying to do something like this, but I just can’t figure out what styles need to be specified so that FAB can overlap the navigation bar. Any ideas?

### **Current version**
![2020-03-02_18-08-43](https://user-images.githubusercontent.com/5754944/75688867-454f1980-5cb1-11ea-8d88-fca5f74f76c2.png)

**Comment by timomeh** [comment]
It's not supported: https://github.com/timomeh/react-native-material-bottom-navigation#updated-material-design-specs
