### ISSUE TITLE
Readme - Bottom Navigation props incorrect name

### ISSUE THREAD

**Issue by prashantham** [timomeh/react-native-material-bottom-navigation#17]
activelabelColor - should have been activeLabelColor

**Comment by timomeh** [comment]
You're absolutely right! Do you want to open a PR or should I fix it in the 
README?

**Comment by prashantham** [comment]
Have not done any PR. I will give it a try.

**Comment by timomeh** [comment]
Docs are always a good way to get into PRs. Try it, don't panic, I won't bite.

**Comment by timomeh** [comment]
Closed with #18.
