### ISSUE TITLE
Cannot change the label style

### ISSUE THREAD

**Issue by ghost** [timomeh/react-native-material-bottom-navigation#19]
Cannot change the font size and family of the label Text. Either we need a label style prop or just use labelStyle in react navigation
`tabBarOptions: {
  labelStyle: {
    fontSize: 12,
  }
}`

**Comment by timomeh** [comment]
`labelStyle` is intentionally not supported. You're only able to change the color of the label using `labelColor`.

Please refer to https://github.com/timomeh/react-native-material-bottom-navigation/issues/15#issuecomment-285116249 for a full explanation, why certain things aren't supported. I'm thinking about making a more customizable Bottom Navigation / Tab Bar, but this Package should encourage developers to follow Google's Guidelines.

**Comment by nzrsrk** [comment]
> labelColor

i cant change label color using labelColor.. how its possible..please help me

**Comment by timomeh** [comment]
@nzrsrk labelColor is not an option anymore since version 1. Please read the docs.
