### ISSUE TITLE
changing the font of tabs labels

### ISSUE THREAD

**Issue by rawris** [timomeh/react-native-material-bottom-navigation#22]
I'm trying to change the font of the tabs label but labelStyle doesn't work.

**Comment by timomeh** [comment]
`labelStyle` is intentionally not supported. You're only able to change the color of the label using `labelColor`.

Please refer to https://github.com/timomeh/react-native-material-bottom-navigation/issues/15#issuecomment-285116249 for a full explanation, why certain things aren't supported. I'm thinking about making a more customizable Bottom Navigation / Tab Bar, but this Package should encourage developers to follow Google's Guidelines.
