### ISSUE TITLE
Tab ripples twice when tapped

### ISSUE THREAD

**Issue by pylSER** [timomeh/react-native-material-bottom-navigation#27]
I am using this navigation with react navigation TabNavigator. Just followed the Readme.
It turns out that when I tap a tab it ripples twice.
 I have to wait for next screen for more than one second. 
This is kind of disturbing.
PS:  Tab will ripple once if the screen is swiped. But there is still a delay for about 1 second.

**Comment by timomeh** [comment]
Yeah, you're right. I think I need some shouldComponentUpdate logic for this. Definitely needs to be fixed.

**Comment by timomeh** [comment]
I just released v0.5.1 which should fix the flickering of the tab ripple. Should be gone if you update.

Please re-open if there are any more issues regarding this, which I may forgot.
