### ISSUE TITLE
Navigate between screens

### ISSUE THREAD

**Issue by JVRodrigues256** [timomeh/react-native-material-bottom-navigation#30]
Hello everyone, I'm using react-native-material-bottom-navigation to navigate between screens in my application, however I do not know how to take the user to another screen when clicking a button, 'onPress' does not seem to work.

Does anyone know how I can take the user to another screen?

**Comment by timomeh** [comment]
You can listen to changes of the active Tab with the `onTabChange` prop. There's an [example in the README](https://github.com/timomeh/react-native-material-bottom-navigation#but-how) along with [all available configs](https://github.com/timomeh/react-native-material-bottom-navigation#bottomnavigation).

In this callback you can change the active screen.

There's also an [example for handling tabChange in a stateful component](https://github.com/timomeh/react-native-material-bottom-navigation/blob/e5560123c345901b4a4d397837ff4846075a2ffe/example/StatefulBottomNavigaion.js), which can come handy.
