### ISSUE TITLE
How does react-navigation add buttons in the center?

### ISSUE THREAD

**Issue by webLiu** [timomeh/react-native-material-bottom-navigation#34]
How does react-navigation add buttons in the center?,Thank you!
![image](https://user-images.githubusercontent.com/12458173/28499354-5c3cb144-6fe6-11e7-9045-f079ba45c30c.png)

**Comment by timomeh** [comment]
That's not really supported. If you want a button in the center which navigates to a view without the TabBar, the only possibility would be to use a normal tab which looks like a button, connected to a screen which has `tabBarVisible: false`.

If you're searching for a way to customize this tab/button, I plan a rewrite of this component, see https://github.com/timomeh/react-native-material-bottom-navigation/issues/31#issuecomment-310229009.

**Comment by webLiu** [comment]
think U!
