### ISSUE TITLE
How to remove resizing animation?

### ISSUE THREAD

**Issue by muzammil-triffort** [timomeh/react-native-material-bottom-navigation#37]
Is this possible to remove the resizing animation while switching to other tabs? Thanks in advance.

**Comment by timomeh** [comment]
Not in this version. This component will have some un-customizable behaviours which are according to the Material Guideliens. For an explanation see https://github.com/timomeh/react-native-material-bottom-navigation/issues/15#issuecomment-285116249.

If you need custom behaviour, you have to fork it, remove the animation from the code and use your own repo in your app.

But I'm started to work on a new component (as time allows) which aims to be highly customizable. Stay tuned for that.

**Comment by muzammil-triffort** [comment]
Okay Thanks!
