### ISSUE TITLE
Switches automatically between Fixed Navigation (up to 3 tabs) and Shifting Navigation (3 - 5 tabs)

### ISSUE THREAD

**Issue by ghost** [timomeh/react-native-material-bottom-navigation#38]
Hi, 
Is it possible   to customize more then 3 images without shifting ?

**Comment by timomeh** [comment]
You can manually set shifting, see [README.md#Configuration](https://github.com/timomeh/react-native-material-bottom-navigation#configuration)

(Related to https://github.com/timomeh/react-native-material-bottom-navigation/issues/14#issuecomment-298141038)

Use the prop `shifting={false}`.

I hope that solves your question. If not, please feel free to reopen this issue.

**Comment by ghost** [comment]
Thanks.  @timomeh
