### ISSUE TITLE
Icon + Text is not centered

### ISSUE THREAD

**Issue by Ehesp** [timomeh/react-native-material-bottom-navigation#39]
Hey,

We've got `shifting` set to false on our app, and it's quite obvious the icons don't seem to be aligned in the center above the text:

![image](https://user-images.githubusercontent.com/842078/29526151-c1d95b26-868c-11e7-9b98-ae6f8fe6d27b.png)

Putting this into PS:

![image](https://user-images.githubusercontent.com/842078/29526297-32f3b586-868d-11e7-9f25-deceab14e1f3.png)

I'll double check it's not something to do with the view being out of place around the icon (directly from react-native-material-icons) though.

**Comment by timomeh** [comment]
Thanks for reporting! That's strange, the Icon should be centered thanks to `flex` and `alignItems: 'center'`. https://github.com/timomeh/react-native-material-bottom-navigation/blob/e5560123c345901b4a4d397837ff4846075a2ffe/lib/Tab.js#L266-L271

Is your Icon set to `size={24}`? (See [Specs of Tab](https://github.com/timomeh/react-native-material-bottom-navigation#tab) – the Icons are required to have a width and height of 24, so the animations are precise to Google's Specs.)

If you've checked that and compared with the examples ([for react-navigation](https://github.com/timomeh/react-native-material-bottom-navigation/blob/master/example/ReactNavigationBottomNavigation.js) or [as standalone](https://github.com/timomeh/react-native-material-bottom-navigation/blob/master/example/SimpleBottomNavigation.js)) and it's still misaligned, please respond and I'll fire up an emulator and try to check it.

**Comment by Ehesp** [comment]
Ah you're correct, they were set to 20. I guess it makes sense how you've implemented it though! Sorry for bothering haha.

**Comment by timomeh** [comment]
Aaah, what a relief! 😅
