### ISSUE TITLE
How To go to next screen

### ISSUE THREAD

**Issue by bisht2ankit** [timomeh/react-native-material-bottom-navigation#41]
Can you tell me how to show different screens on clicking on tab bar items?

**Comment by timomeh** [comment]
You asked the exact same question yesterday and I already answered: https://github.com/timomeh/react-native-material-bottom-navigation/issues/40

The task of this library isn't navigating. This is a UI component. If you want to navigate, use [react-navigation](https://github.com/react-community/react-navigation/). They have a great documentation. Or look/ask on [stackoverflow](https://stackoverflow.com).
