### ISSUE TITLE
The navigation disappears when pressing the button

### ISSUE THREAD

**Issue by moonlinefoolks** [timomeh/react-native-material-bottom-navigation#50]
I have a navigation menu in it there are several buttons, when I press the button in the navigation menu. as a result my navigation menu disappears, and its label follows the title I have set in `staticNavigationOptions`. I try `position: 'absolute'` and `flex: 1`, the navigation disappears. how to fix it?
normal navigation:
![asdaw](https://user-images.githubusercontent.com/29745799/31487550-30f7fcfa-af65-11e7-86c4-b51cd9f76d7c.jpg)

when i press the menu navigable button:
![home](https://user-images.githubusercontent.com/29745799/31487727-ad7642fa-af65-11e7-8057-d5bc4909a079.jpg)

**Comment by timomeh** [comment]
You didn't fill out the issue template, so I have to close this issue. Please open a new issue and read the pre-filled text instead of deleting it. Answer all the questions of the template.

**Comment by moonlinefoolks** [comment]
sorry sir, I'm a little panic

**Comment by timomeh** [comment]
That's no problem, you don't have to panic.
