### ISSUE TITLE
The navigation disappears when pressing the button

### ISSUE THREAD

**Issue by moonlinefoolks** [timomeh/react-native-material-bottom-navigation#51]
### What kind of Issue is this?

- () Bug Report
- (x) Question / Problem
- () Discussion / Feature Request

### How are you using the Bottom Navigation?

- (x) I use the Bottom Navigation together with react-navigation; the Issue is not appearing when I'm using react-navigation's TabBar instead.
- () I use the standalone version.

Related Libraries: (If you use the standalone version together with other libraries, please list them here. If not, delete this line.)

### Expected behavior

(how to make the navigation work properly??)

### Actual behavior

(The navigation disappears when pressing the button )

### Additional description and resources

(I have a navigation menu in it there are several buttons, when I press the button in the navigation menu. as a result my navigation menu disappears, and its label follows the title I have set in `staticNavigationOptions`. I try `position: 'absolute'` and `flex: 1`, the navigation disappears.)

(normal navigation:
![asdaw](https://user-images.githubusercontent.com/29745799/31504535-d32feff0-af9c-11e7-9d5e-85c5fb17450b.jpg)
)
when i press the menu navigable button:
![home](https://user-images.githubusercontent.com/29745799/31504564-e0c554b6-af9c-11e7-96d1-890f31ec905c.jpg)
my code snippet:
![code](https://user-images.githubusercontent.com/29745799/31504680-358f88fe-af9d-11e7-9388-1c8bbbd96ef7.jpg)

### What did you do to find a solution?

(I have done a lot of things for this case, I am looking for these solutions in Github and stackoverflow and Docs)

### Environment

- **React Native versions:** (react-native-cli: 2.0.1, react-native: 0.48.4)
- **react-native-material-bottom-navigation version:** (0.5.2)
- **react-navigation version:** (1.0.0-beta.11)
- I tested this with: (Android)

**Comment by timomeh** [comment]
So, to clarify, your problem is that "Menu" changes to "Berita" and the Menu-Icon disappears?

If you take a look at: https://reactnavigation.org/docs/navigators/tab
In those docs you can see `navigationOptions.tabBarLabel` and `navigationOptions.tabBarIcon`, where you need to specify the label and icon for this screen. If you set those to "Menu" and to your Menu Icon, it should be correct.

**Comment by moonlinefoolks** [comment]
Thanks for a quick reply, it is working
