### ISSUE TITLE
Add badges

### ISSUE THREAD

**Issue by mschipperheyn** [timomeh/react-native-material-bottom-navigation#52]
I use bottom navigation among other things for notifications, which have a "new count" badge. 
It would be a nice option to be able to add a new count like this. This should be a string or icon not a number, because for large volume, you want to use "2,5k", "1.1M" etc.

Badges are kind of an implied part of Material Design that are referenced more commonly with Material Design Lite.

E.g.
https://getmdl.io/components/#badges-section

**Comment by timomeh** [comment]
Thank you for your suggestion! I also agree about the implied nature of badges.

I'm planning a new major version of the bottom navigation with less restrictions (see https://github.com/timomeh/react-native-material-bottom-navigation/issues/31#issuecomment-310229009), which would be a good time to implement badges. I'm currently writing a thesis, so unfortunately I don't have any time at the moment to do *anything* except writing the thesis.

Of course, you – or anyone reading this – can also contribute by adding this feature.

**Comment by Angelk90** [comment]
@mschipperheyn , @timomeh : Are there any news?

**Comment by ShayanJavadi** [comment]
@timomeh @Angelk90 I just came across the need for this feature. I will make this feature in a few days. however I'm going to be using the badge from [react-native-material-ui](https://github.com/xotahal/react-native-material-ui/blob/master/docs/Badge.md) so I doubt that @timomeh would want to merge my changes to the project since I'm guessing he'd like to stay dependency free (am I right about this @timomeh ?).

So I'll make a fork and put the link for it here. stay tuned.

**Comment by ShayanJavadi** [comment]
here's my attempt: https://github.com/ShayanJavadi/react-native-material-bottom-navigation
<img width="259" alt="screen shot 2018-02-04 at 2 22 45 am" src="https://user-images.githubusercontent.com/11575429/35775641-59cf0fd2-0952-11e8-99e0-8018f6184a66.png">

made a pr: https://github.com/timomeh/react-native-material-bottom-navigation/pull/70

**Comment by Angelk90** [comment]
@ShayanJavadi : 
Hi, you could do two things:
1) You could publish a gif of the result.
2) You could try it on a different resolution big moltopiu, example tablet is to publish a gif of the result.

Thx.

**Comment by ShayanJavadi** [comment]
@Angelk90 [gif](http://recordit.co/t9ffQW7VuX)

**Comment by timomeh** [comment]
Thanks to @ShayanJavadi, this got merged in #70 and released in v0.8.0

**Comment by Nazeercs** [comment]
> here's my attempt: https://github.com/ShayanJavadi/react-native-material-bottom-navigation
> <img alt="screen shot 2018-02-04 at 2 22 45 am" width="259" src="https://user-images.githubusercontent.com/11575429/35775641-59cf0fd2-0952-11e8-99e0-8018f6184a66.png">
> 
> made a pr: #70

hello sir..how to add more than one bdage in icons in material-bottom-navigation

**Comment by Nazeercs** [comment]
@ShayanJavadi @timomeh  hello sir Please help me..how to add more than one badge in the icons in material bottom navigation.. now possible to add one badge any one of bottom icon in current example. need badge count for home and notification section.
