### ISSUE TITLE
Disable horizontal scroll for tab

### ISSUE THREAD

**Issue by roofiah** [timomeh/react-native-material-bottom-navigation#53]
how to disable horizontal scroll for tab menu?

**Comment by timomeh** [comment]
Could you please explain further what you mean by horizontal scroll? There should be no horizontal scroll on the BottomNavigation.

**Comment by roofiah** [comment]
i want to disable horizontal scroll when shifting the screen. so only move to another tab when clicking the tab. what's the solution @timomeh ?. thanks

**Comment by timomeh** [comment]
Sorry, but I don't understand what you mean by "disable horizontal scroll when shifting the screen". The BottomNavigation shouldn't/can't scroll horizontally. Can you please show your behaviour in a gif?

**Comment by yuni27** [comment]
maybe @roofiah mean like this. 
![screenrecording_20171101_091805 1](https://user-images.githubusercontent.com/33209832/32312058-4684e186-bfce-11e7-9f05-8c29fa05f907.gif)

**Comment by yuni27** [comment]
can u play this gif?
I also had a problem with button navigation. Is possible to make the screen only change when we tap the button, so if we scroll the screen it wont change or stay in that screen.
thanks before

**Comment by timomeh** [comment]
I can't play the gif. I need some kind of reproduction in order to understand this issue.

Are you using the BottomNavigation with react-navigation or without?

**Comment by timomeh** [comment]
Do you maybe mean, that the Tab changes if you swipe left or right? That's a react-navigation feature. You can disable this behaviour with `swipeEnabled: false`, see here: https://reactnavigation.org/docs/navigators/tab

**Comment by yuni27** [comment]
OK thanks alot... its work :)
