### ISSUE TITLE
how to change icon using my own icon

### ISSUE THREAD

**Issue by yuni27** [timomeh/react-native-material-bottom-navigation#57]
I wanna change the icon with my own icon (icon.io),  at the default it using react element. Can u explain how to change it? thanks before

**Comment by timomeh** [comment]
Take a look at the documentation at https://oblador.github.io/react-native-vector-icons/, there's a section for own icons.

I'm going to close this issue since it's not related to this project.

**Comment by yuni27** [comment]
i mean, i wanna change the icon from my own folder, not from that react native icon.

**Comment by timomeh** [comment]
As I said, you can use react-native-vector-icons to define own icons. Or use an image or any other icon component you want, the BottomNavigation doesn't care.

**Comment by Dineshchitta** [comment]
I have done like this.

```
import {Image} from 'react-native'
const ownIcon = React.createElement(Image, {
  source: require('youricon.png')
})
```
Usage with Tab
```
<Tab
   label={'Home'}
   icon={ownIcon}
  />
```
