### ISSUE TITLE
navigationState.routes.map((route, index)   react-navigation  navigationState.routes  no route

### ISSUE THREAD

**Issue by syanbo** [timomeh/react-native-material-bottom-navigation#60]
react-navigation "^1.0.0-beta.21"
react-native-material-bottom-navigation "^0.6.1
navigationState.routes.map((route, index) react-navigation navigationState.routes no route

**Comment by timomeh** [comment]
Please create a new Issue and fill out the provided Issue Template, and explain your problem. Currently I have no idea what you mean 😅
