### ISSUE TITLE
(Android) react-navigation >= beta.20 doesn't work

### ISSUE THREAD

**Issue by wildseansy** [timomeh/react-native-material-bottom-navigation#61]
### What kind of Issue is this?
- Bug Report

### How are you using the Bottom Navigation?
Using `react-navigation` with `react-native-material-bottom-navigation` on Android. App crashes when starting with error:
```
Undefined is not an object(evaluating '_ref4.route') 
```
...on Android only.

Originally posted here: https://github.com/react-community/react-navigation/issues/3020, but was found to only crash when used with `react-native-material-bottom-navigation`

Stacktace:
<img src="https://user-images.githubusercontent.com/30583152/33054641-0dfeb088-cead-11e7-8d30-78679df6c500.png" height=500 />

### Expected behavior

App should start appropriately with material bottom navigation

### Actual behavior

App crashes with above stacktrace 

### Additional info
React Navigation had this same crash in beta.20, they fixed it on their side in beta.21 [in this commit](https://github.com/react-community/react-navigation/commit/4750901b3904330c8a62e511c44af9084a145acc)

### Environment

- **React Native versions:** 0.50.4
- **react-native-material-bottom-navigation version:** v0.6.1
- **react-navigation version:** beta.20 and greater
- **I tested this with:** Android

**Comment by nonameolsson** [comment]
I'm experiencing the same problem. Any solution on this?

**Comment by timomeh** [comment]
Thanks for reporting this issue! I'll have to look into it, but I don't have time this week. For now I'd suggest using react-navigation beta.19 (someone confirmed it works). Or if someone wants to look into it, go ahead and ping me here!

**Comment by keeleycarrigan** [comment]
I think I [figured it out](https://github.com/timomeh/react-native-material-bottom-navigation/pull/62/files)

**Comment by timomeh** [comment]
Fixed with version 0.7.0. Thank you, @keeleycarrigan!
