### ISSUE TITLE
onPress on tab not working

### ISSUE THREAD

**Issue by akhilesh08061** [timomeh/react-native-material-bottom-navigation#65]
onTabChange is perfectly working in react native material bottom navigation.but as given in a documentation that you can even use onPress on individual tabs.but it is not working for my case.
example:-
`<BottomNavigation>
    <Tab 
    onPress={(newTabIndex)=>console.log(newTabIndex)}
    label="movie"
    icon={<Image src={require("image address")}/>
}
/>
</BottomNavigation>`

**Comment by timomeh** [comment]
If you use `onPress`, you have to handle `activeTab` by yourself. See this working example: https://snack.expo.io/rJzZgos7f

The docs are very explicit about this behavior:

> Function to be called when the Tab was pressed. **When you use this, the pressed tab won't be active automatically. You need to set it to active by updating `BottomNavigation.activeTab`.**

I would advise _against_ using `onPress` and recommend using `onTabChange`. The `onPress` prop exists mainly to support react-navigation.

**Comment by akhilesh08061** [comment]
Thank you very much.i will try your solution.
