### ISSUE TITLE
Fixed mode tinting

### ISSUE THREAD

**Issue by AlirezaAkbarix** [timomeh/react-native-material-bottom-navigation#78]
Set `shifting : false` should make bottomNav as **`Fixed`**(?), by doing it, how to tint label and icon to desired color as shown in repo gifs?

**Comment by timomeh** [comment]
If you want to change the label- and icon-color, check the Documentation sections [#BottomNavigation](https://github.com/timomeh/react-native-material-bottom-navigation#bottomnavigation) and [#Tab](https://github.com/timomeh/react-native-material-bottom-navigation#tab). The props you are searching for are called `activeIcon` and `activeLabelColor`. You can check the [examples](https://github.com/timomeh/react-native-material-bottom-navigation/blob/master/examples/SimpleBottomNavigation.js) if you don't know how to set those props, or take a look at [#Usage](https://github.com/timomeh/react-native-material-bottom-navigation#usage).

Styling works the same for shifting and non-shifting Tabs.
