### ISSUE TITLE
Change BadgeText from the screen

### ISSUE THREAD

**Issue by patrickmuhi** [timomeh/react-native-material-bottom-navigation#81]
### What kind of Issue is this?

- (x) Bug Report

### How are you using the Bottom Navigation?

- (x) I use the Bottom Navigation together with react-navigation; the Issue is not appearing when I'm using react-navigation's TabBar instead.

### Expected behavior

If there was a way to dynamically change the badgeText using something like the `navigationOptions` from the corresponding screen.

### Actual behavior

badgeText is only set from when creating the StackNavigator

### Environment

- **React Native versions:** 0.53
- **react-native-material-bottom-navigation version:** 0.9.0
- **react-navigation version:** 1.0.0-beta.11 
- **I tested this with:** Android | iOS |

**Comment by timomeh** [comment]
I'm currently working on a complete rewrite #76. I will keep this bug/feature in mind when I create the new react-navigation integration.

**Comment by timomeh** [comment]
Closed with release of v1.0.0
