### ISSUE TITLE
How to style TabNavigator and place icons in tabs?

### ISSUE THREAD

**Issue by joaoalbertocsjunior** [timomeh/react-native-material-bottom-navigation#82]
Good day.

My question is simple. How to style TabNavigator and place icons in tabs?

**Comment by timomeh** [comment]
Usage with react-navigation is documented [in the README](https://github.com/timomeh/react-native-material-bottom-navigation#usage-with-react-navigation) and there's also [an example here](https://github.com/timomeh/react-native-material-bottom-navigation/blob/7961136dfe628f5de407a6287b5e8c8d8b420442/examples/ReactNavigationBottomNavigation.js). Additionally there's a [documentation in react-navigation](https://reactnavigation.org/docs/tab-navigator.html) on how to style the TabNavigator. Please notice that the current BottomNavigation version 0.9.0 doesn't support all the styles which react-navigation supports.

If there's anything unclear, please explain what's missing in the docs or poorly explained. Thank you!
