### ISSUE TITLE
Bottomview cover whole screen? and position click issue

### ISSUE THREAD

**Issue by ZeroCool00** [timomeh/react-native-material-bottom-navigation#83]
After implementing  bottomview i m not able to add other view's 

```
screenRender() {
		if (this.state.screen === 0) {
			return <Workspace />;
		} else if (this.state.screen === 1) {
      return <Account />;
    }
  }

render() {
      return (
        <Text>Hello</Text> // not showing 
        <View style={styles.container}>
          {this.screenRender()}
          <BottomNavigation
            labelColor="white"
            rippleColor="white"
            style={styles.bottomBarStyle}
            innerStyle={{ paddingBottom: 48 }}
            onTabChange={(newTabIndex) => this.setState({ screen: newTabIndex })}
          >
         ........
        </BottomNavigation>
      </View>
      );
    }
```

and if i click on position 2 its render position 0 , if i click on position 3 it render position 0. i have to select twice per each position to be selected, first time its always render position 0,

see there is no text showing in screen, bottomview should be wrap to bottom
![whatsapp image 2018-04-24 at 2 14 13 pm](https://user-images.githubusercontent.com/18139594/39176210-e88d1bbe-47c9-11e8-99ac-ed47aee0b0a5.jpeg)

**Comment by ZeroCool00** [comment]
Bottomview cover whole screen is Fix now..  i remove styles.xml and its working now.. it seems windowTranslucentNavigation covering the whole screen, it fix but now i m not able to animate navigationbar,

about second issue is still remain.. 
no matter what position i select it is animating index = 0 position.

**Comment by timomeh** [comment]
In order to set a tab to active, use `<BottomNavigation activeTab={this.state.screen} ...`

**Comment by ZeroCool00** [comment]
@timomeh  i get it now.. thanks for the quick reply.
