### ISSUE TITLE
is it possible to make scrollable bottomview if item has more than 4

### ISSUE THREAD

**Issue by ZeroCool00** [timomeh/react-native-material-bottom-navigation#84]
what if i have more than 4 menu item and want to make it scrollable.. is it possible ?

and how to make center item overlap other view like this.
![tab-bar-icons-iphone-ramotion-animation-interface-design](https://user-images.githubusercontent.com/18139594/39184674-fd048506-47e1-11e8-9538-d71ece25b2de.gif)

or like this:

![screen shot 2018-04-24 at 5 08 48 pm](https://user-images.githubusercontent.com/18139594/39184763-550cf9f4-47e2-11e8-870f-8a4120c0b5bc.png)

**Comment by timomeh** [comment]
Unfortunately you can't make the bottom navigation scrollable, and also you can't make a tab bigger
