### ISSUE TITLE
could use updates for react-navigation support. Does not pass navigation prop on tabPress.

### ISSUE THREAD

**Issue by j-mendez** [timomeh/react-native-material-bottom-navigation#86]
### What kind of Issue is this?

- () Bug Report
- () Question / Problem
- () Discussion / Feature Request

### How are you using the Bottom Navigation?

- () I use the Bottom Navigation together with react-navigation; the Issue is not appearing when I'm using react-navigation's TabBar instead.
- () I use the standalone version.

Related Libraries: {If you use the standalone version together with other libraries, please list them here. If not, delete this line.}

### Expected behavior

{Write down what you expected to happen. Add code snippets later.}

### Actual behavior

{Write down what is actually happening. Add code snippets later.}

### Additional description and resources

{Write down everything else you want to say.}

{Place a reproducible example here.  
The best thing you can do is to provide a minimal example which reproduces your Issue in Expo's Snack: https://snack.expo.io  
Otherwise: Add all relevant Code Snippets here. Add screenshots/gifs showing your issue in action.}

### What did you do to find a solution?

{List all the things you've done and/or places and search-terms you used to find a solution.}

### Environment

- **React Native versions:** {Insert here.}
- **react-native-material-bottom-navigation version:** {Insert here.}
- **react-navigation version:** {Insert here.} 
- **I tested this with:** {Please choose one or more: Android | iOS | Web | Windows}

**Comment by timomeh** [comment]
You submitted the blank Issue Template. Please fill out the Issue Template.

**Comment by timomeh** [comment]
I'm going to close this issue since the blank issue template was submitted, and v1.0.0 dropped native support for React Navigation.
