### ISSUE TITLE
Does not respond to dynamic state updates.

### ISSUE THREAD

**Issue by j-mendez** [timomeh/react-native-material-bottom-navigation#87]
Use a central store like mobx and try to adjust the colors and it does not properly update.

**Comment by timomeh** [comment]
Please provide more informations and a reproductible example. The Issue Template lists all common informations which are necessary for a good issue.

**Comment by timomeh** [comment]
I'm going to close this issue due to inactivity and lack of informations. Please check out version 1.0.0. If you still encounter issues, open a new Issue with a more details description.
