### ISSUE TITLE
Not getting selected tab name

### ISSUE THREAD

**Issue by sandeepsinghs** [timomeh/react-native-material-bottom-navigation#91]
While selecting specific tab from bottom navigation bar and trying to log the name of selected tab then getting as  [object Object]. 

I want to know the selected tab so that I can navigate to specific screen.

Please help.

**Comment by timomeh** [comment]
`onTabChange` has as parameter the tab object, not only the tab key. You can get the key with

```
onTabChange = newTab => {
  console.log(newTab.key)
}
```

It seems like the documentation is wrong about that. I'm going to fix that.

**Comment by timomeh** [comment]
Sorry, of course it's `onTabPress`, not `onTabChange`.

**Comment by sandeepsinghs** [comment]
Thank you @timomeh

**Comment by sandeepsinghs** [comment]
I need one more help please.

After knowing pressed name of tab I need to replace the above View of **BottomNavigation** to other specific view act as navigating to multiple view on clicks of tab.

I am beginner for react native. Please help.

**Comment by timomeh** [comment]
I updated the wrong docs, thus I'm going to close this issue. Thank you for pointing this out.

> After knowing pressed name of tab I need to replace the above View of BottomNavigation to other specific view act as navigating to multiple view on clicks of tab.

For this case you need a Navigation Library, such as [react-navigation](https://github.com/react-navigation/react-navigation) or [react-native-navigation](https://github.com/wix/react-native-navigation). Navigating is not a part of react-native-material-bottom-navigation.
