### ISSUE TITLE
How to show labels for inActive tab in 0.9.0

### ISSUE THREAD

**Issue by Dineshchitta** [timomeh/react-native-material-bottom-navigation#92]
### What kind of Issue is this?
 
Question

### Actual behavior

- What is happening?
   Not showing labels for inactive tabs 
- Is it happening on Android, iOS or both?
   Checked in Android only.

### Expected behavior

- What did you expect to happen?
   Wanted to show labels for inactive tabs as well

### Environment

| software                                | version
| --------------------------------------- | ------- 
| react-native-material-bottom-navigation | 0.9.0
| react-native or expo                    |  0.48.4
| node                                    |  v9.10.1
| npm or yarn                             | 6.0.0

**Comment by timomeh** [comment]
The Tabs (in "shifting" mode) in v0.9.0 only show the label when they're active. You can get around this by disabling shifting mode...

```js
<BottomNavigation shifting={false} />
```

...or by updating to v1.0.0.
