### ISSUE TITLE
Is there anyway to change tab programmatically

### ISSUE THREAD

**Issue by huy-lv** [timomeh/react-native-material-bottom-navigation#95]
Hello, your project is awesome, but i have a question, is there anyway to change tab programmatically. Code should be like this
```
let newIndex = 2
this.tab_ref.changeTo(newIndex);
```

**Comment by timomeh** [comment]
There's no API via a ref. You can use the Bottom Navigation as controlled component to change the active tab programatically: https://github.com/timomeh/react-native-material-bottom-navigation/blob/master/docs/Usage.md#controlled-component

Executing methods on a component via a ref is a bit of an antipattern in React.
