### ISSUE TITLE
How to change color of selected icon and label

### ISSUE THREAD

**Issue by ZeroCool00** [timomeh/react-native-material-bottom-navigation#96]
is it possible to change only icon and text color when its selected? i cant find any props regarding selected tab.

**Comment by timomeh** [comment]
The render prop for `renderTab` and `renderIcon` receive the key `isActive` as argument, which is true when the Tab is selected.

See Usage here: https://timomeh.gitbook.io/material-bottom-navigation/usage#rendering-a-tab, especially the `renderTab` method in the code example of the Section _"Rendering a Tab"_.

```js
export default class App extends React.Component {
  render() {
    return (
      <View>
        <BottomNavigation
          renderTab={this.renderTab}
          tabs={/* ... */}
        />
      </View>
    )
  }
  ​
  renderTab = ({ tab, isActive }) => { // <- `isActive` here
    return (
      <FullTab
        key={tab.key}
        isActive={isActive} // <- `isActive` here
        label={tab.label}
        renderIcon={this.renderIcon}
      />
    )
  }
​
  renderIcon = ({ isActive }) => {  // <- `isActive` here
    return /* ... */
  }
}
```

Does that solve your problem?

**Comment by ZeroCool00** [comment]
i am able to change icon color when its selected:

```
renderIcon = (icon, isActive) => () => (
    isActive ? <Icon size={24} type='MaterialCommunityIcons' style={styles.ic} name={icon} /> :
    <Icon size={24} type='MaterialCommunityIcons' name={icon} />
  )
```

but no luck in label.

**Comment by timomeh** [comment]
The Tab has a prop called `labelStyle`, which you can use to customize the label. See the Component Specs here: https://timomeh.gitbook.io/material-bottom-navigation/api-reference/fulltab#labelstyle

```js
renderTab = ({ tab, isActive }) => {
  return <FullTab
    labelStyle={{
      color: isActive ? 'green' : 'white'
    }}
  />
}
```

**Comment by ZeroCool00** [comment]
Thank you so much.. its solve now..

now its look like this.
![bottombar](https://user-images.githubusercontent.com/18139594/41661609-bafddefc-74bc-11e8-947f-21ad6b183a9c.png)

**Comment by timomeh** [comment]
No problem. 🙂
